<?xml version="1.0"?>
<robot name="ip50_sim" xmlns:xacro="https://ros.org/wiki/xacro">
  <xacro:arg name="lidar_visual" default="true" />

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>

  <gazebo reference="front_left_wheel_link">
    <kp>1000000.0</kp>
    <kd>1</kd>
    <mu1>2000.0</mu1>
    <mu2>1000.0</mu2>
    <minDepth>0.0005</minDepth>

    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="front_right_wheel_link">
    <kp>1000000.0</kp>
    <kd>1</kd>
    <mu1>2000.0</mu1>
    <mu2>1000.0</mu2>
    <minDepth>0.0005</minDepth>

    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="back_left_wheel_link">
    <kp>1000000.0</kp>
    <kd>1</kd>
    <minDepth>0.0005</minDepth>

    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="back_right_wheel_link">
    <kp>1000000.0</kp>
    <kd>1</kd>
    <minDepth>0.0005</minDepth>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>${update_rate}</updateRate>
      <leftJoint>front_left_wheel_joint</leftJoint>
      <rightJoint>front_right_wheel_joint</rightJoint>
      <wheelSeparation>${front_wheel_pos_y * 2}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <wheelAcceleration>2.0</wheelAcceleration>
      <wheelTorque>10000</wheelTorque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <odometrySource>world</odometrySource>
      <publishOdomTF>true</publishOdomTF>
      <publishTF>true</publishTF>
      <publishWheelTF>false</publishWheelTF>
      <publishOdom>true</publishOdom>
      <publishWheelJointState>true</publishWheelJointState>
      <legacyMode>false</legacyMode>
      <rosDebugLevel>na</rosDebugLevel>
    </plugin>
  </gazebo>

  <gazebo reference="xsens_imu_link">
    <gravity>true</gravity>
    <sensor name="base_imu" type="imu">
      <always_on>true</always_on>
      <visualize>false</visualize>
      <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
        <topicName>imu/data</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHZ>30.0</updateRateHZ>
        <gaussianNoise>0.001</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_link</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>

  <gazebo reference="lidar_link">
    <material>Gazebo/Black</material>
    <sensor type="ray" name="soslab_gl_3">
      <pose>0 0 0 0 0 0</pose>
      <visualize>$(arg lidar_visual)</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>2000</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.05</min>
          <max>25.0</max>
          <resolution>0.003</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.001</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_laser.so">
        <topicName>scan</topicName>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>