<?xml version="1.0" ?>
<!-- ip50 mobile robot -->
<robot name="ip50" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ip50_description)/urdf/materials.xacro"/>
  <xacro:include filename="$(find ip50_description)/urdf/properties.xacro"/>

  <link name="base_footprint"/>

  <link name="base_link">
  </link>

  <link name="center_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename= "package://ip50_description/meshes/base.dae" scale="1 1 1"/>
      </geometry>
      <material name="orange" />
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename= "package://ip50_description/meshes/base.dae" scale="1 1 1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.01103 0 0.002" rpy="0 0 0"/>
      <mass value="70" />
      <inertia ixx="1.225" ixy="0.0099" ixz="0.0062" iyy="1.2853" iyz="-0.0034" izz="0.987" />
    </inertial>
  </link>


  <link name="front_left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <mass value="4.0" />
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.0045" />
    </inertial>
  </link>

  <link name="front_right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <mass value="4.0" />
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.0045" />
    </inertial>
  </link>

  <link name="back_right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <mass value="4.0" />
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.0045" />
    </inertial>
  </link>

  <link name="back_left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <mass value="4.0" />
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.0045" />
    </inertial>
  </link>

  <joint name="base_link_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 ${0.03 + wheel_radius}" rpy="0 0 0" />
  </joint>

  <joint name="center_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="center_link" />
    <origin xyz="${-front_wheel_pos_x} 0 0" rpy="0 0 0" />
  </joint>


  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="center_link"/>
    <child link="front_left_wheel_link" />
    <origin xyz="${front_wheel_pos_x} ${front_wheel_pos_y} ${front_wheel_pos_z}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="front_right_wheel_joint" type="continuous">
    <origin xyz="${front_wheel_pos_x} ${-front_wheel_pos_y} ${front_wheel_pos_z}"  rpy="0 0 0" />
    <parent link="center_link"/>
    <child link="front_right_wheel_link" />
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="back_right_wheel_joint" type="fixed">
    <parent link="center_link"/>
    <child link="back_right_wheel_link"/>
    <origin xyz="${back_wheel_pos_x} ${back_wheel_pos_y} ${back_wheel_pos_z}"  rpy="0 0 0" />
  </joint>

  <joint name="back_left_wheel_joint" type="fixed">
    <parent link="center_link"/>
    <child link="back_left_wheel_link"/>
    <origin xyz="${back_wheel_pos_x} ${-back_wheel_pos_y} ${back_wheel_pos_z}"  rpy="0 0 0" />
  </joint>

  <!-- <link name="imu_link"/> -->

  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ip50_description/meshes/LIDAR.dae" scale="1 1 1"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ip50_description/meshes/LIDAR.dae" scale="1 1 1"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <!-- <joint name="imu_joint" type="fixed">
    <parent link="center_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0" rpy="0 0 0"/>
  </joint> -->

  <joint name="lidar_link_joint" type="fixed">
    <parent link="center_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.2511 0 0.017" rpy="0 0 0"/>
  </joint>
  <!-- The diff between  0.2m -->

<!-- Camera Lidar Calibration -->

  <!-- <joint name="lidar_link_joint" type="fixed">
    <parent link="center_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.0511 0 0.017" rpy="0 0 ${-PI/2}"/>
  </joint>  -->

</robot>
